# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1116, 859)
        self.backgr = QtWidgets.QLabel(Dialog)
        self.backgr.setGeometry(QtCore.QRect(-260, -130, 1911, 1011))
        self.backgr.setStyleSheet("background-color:white;")
        self.backgr.setObjectName("backgr")
        self.rainm = QtWidgets.QLabel(Dialog)
        self.rainm.setGeometry(QtCore.QRect(-10, -40, 1141, 671))
        self.rainm.setText("")
        self.rainm.setPixmap(QtGui.QPixmap("C:\\Users\\niran\\Desktop\\rainva\\Year after year (1).gif"))
        self.rainm.setScaledContents(True)
        self.rainm.setObjectName("rainm")
        self.start = QtWidgets.QLabel(Dialog)
        self.start.setGeometry(QtCore.QRect(190, 640, 361, 201))
        self.start.setText("")
        self.start.setPixmap(QtGui.QPixmap("C:\\Users\\niran\\Desktop\\rainva\\Animated Gif.gif"))
        self.start.setScaledContents(True)
        self.start.setObjectName("start")
        self.stop = QtWidgets.QLabel(Dialog)
        self.stop.setGeometry(QtCore.QRect(590, 640, 341, 181))
        self.stop.setText("")
        self.stop.setPixmap(QtGui.QPixmap("C:\\Users\\niran\\Desktop\\rainva\\Angry Cloud.gif"))
        self.stop.setScaledContents(True)
        self.stop.setObjectName("stop")
        self.startbut = QtWidgets.QPushButton(Dialog)
        self.startbut.setGeometry(QtCore.QRect(290, 680, 171, 91))
        self.startbut.setStyleSheet("background-color:transparent;")
        self.startbut.setText("")
        self.startbut.setObjectName("startbut")
        self.stopbut = QtWidgets.QPushButton(Dialog)
        self.stopbut.setGeometry(QtCore.QRect(680, 680, 171, 91))
        self.stopbut.setStyleSheet("background-color:transparent;")
        self.stopbut.setText("")
        self.stopbut.setObjectName("stopbut")
        self.JSRT = QtWidgets.QLabel(Dialog)
        self.JSRT.setGeometry(QtCore.QRect(290, 810, 181, 41))
        self.JSRT.setObjectName("JSRT")
        self.JSRT_2 = QtWidgets.QLabel(Dialog)
        self.JSRT_2.setGeometry(QtCore.QRect(680, 810, 181, 41))
        self.JSRT_2.setObjectName("JSRT_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.backgr.setText(_translate("Dialog", "TextLabel"))
        self.JSRT.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">START</span></p></body></html>"))
        self.JSRT_2.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">STOP</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
